-- Keymaps
-- vim.keymap.set("n", "<leader>e", "<CMD>ViredOpen<CR>")
-- vim.keymap.set("n", "<leader>fp", "<CMD>ViredProjects<CR>")
vim.keymap.set("n", "<leader>e", "<CMD>Oil<CR>")
vim.keymap.set("n", "<leader>ff", ":FzfLua files<CR>")
vim.keymap.set("n", "<leader>/", ":FzfLua live_grep<CR>")
vim.keymap.set("n", "<leader>th", ":FzfLua colorschemes<CR>")
vim.keymap.set("n", "<leader>bb", ":FzfLua buffers<CR>")
vim.keymap.set("n", "<leader>fe", ":FzfLua diagnostics_workspace<CR>")
vim.keymap.set("n", "<leader>fb", ":Gitsigns blame<CR>")
vim.keymap.set("n", "<leader>fm", ":FzfLua man_pages<CR>")
vim.keymap.set("n", "<leader>ft", vim.lsp.buf.format, {})

-- LSP keymaps
vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action)
vim.keymap.set("v", "<leader>ca", vim.lsp.buf.code_action)
vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename)
vim.keymap.set("n", "gd", ":FzfLua lsp_definitions<CR>")
vim.keymap.set("n", "grr", ":FzfLua lsp_references<CR>")
vim.keymap.set("n", "gi", ":FzfLua lsp_implementations<CR>")
vim.keymap.set("n", "<leader>D", ":FzfLua lsp_typedefs<CR>")
vim.keymap.set("n", "K", vim.lsp.buf.hover)

vim.keymap.set("n", "<leader>#", ":CommentToggle<CR>")
vim.keymap.set("v", "<leader>#", ":CommentToggle<CR>")

vim.keymap.set("n", "<C-u>", "<C-u>zz", { noremap = true, silent = true })
vim.keymap.set("v", "<C-u>", "<C-u>zz", { noremap = true, silent = true })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { noremap = true, silent = true })
vim.keymap.set("v", "<C-d>", "<C-d>zz", { noremap = true, silent = true })

vim.g.undotree_WindowLayout = 3

vim.cmd([[
  autocmd FileType undotree setlocal winwidth=52
]])
vim.keymap.set("n", "<leader>u", vim.cmd.UndotreeToggle)

local harpoon = require("harpoon")

harpoon:setup()

vim.keymap.set("n", "<leader>a", function()
	harpoon:list():add()
end)
vim.keymap.set("n", "<C-e>", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end)

vim.keymap.set("n", "<leader>1", function()
	harpoon:list():select(1)
end)
vim.keymap.set("n", "<leader>2", function()
	harpoon:list():select(2)
end)
vim.keymap.set("n", "<leader>3", function()
	harpoon:list():select(3)
end)
vim.keymap.set("n", "<leader>4", function()
	harpoon:list():select(4)
end)
vim.keymap.set("n", "<leader>5", function()
	harpoon:list():select(5)
end)
vim.keymap.set("n", "<leader>6", function()
	harpoon:list():select(6)
end)
vim.keymap.set("n", "<leader>7", function()
	harpoon:list():select(7)
end)
vim.keymap.set("n", "<leader>8", function()
	harpoon:list():select(8)
end)
vim.keymap.set("n", "<leader>9", function()
	harpoon:list():select(9)
end)
